[versions]
flyway = "13.0.0"
sasGradlePlugins = "20260804.1151"

[libraries]
rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026071513121784113927"

postgresql = "org.postgresql:postgresql:42.7.13"
hikaricp = "com.zaxxer:HikariCP:7.1.0"
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-databasePostgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
kotliquery = "com.github.seratch:kotliquery:1.9.1"
micrometer-registryPrometheus = "io.micrometer:micrometer-registry-prometheus:1.17.0"

logback-classic = "ch.qos.logback:logback-classic:1.6.1"
logback-logstashEncoder = "net.logstash.logback:logstash-logback-encoder:9.0"

mockk = "io.mockk:mockk:1.14.11"
testcontainers-postgresql = "org.testcontainers:testcontainers-postgresql:2.0.5"
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"
tbdLibs-rapidsAndRiversTest = "com.github.navikt.tbd-libs:rapids-and-rivers-test:2025.11.04-10.54-c831038e"

[plugins]
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
