apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spotlight
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
    disableAutoScaling: true
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-f1-micro
        databases:
          - name: spotlight
            envVarPrefix: DATABASE
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
      rules:
        - application: logging
          namespace: nais-system
  envFrom:
    - secret: spotlight-slack
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spotlight-v1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
