/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.helse

import no.nav.helse.rapids_rivers.RapidApplication

class App {
    private val rapidsConnection = RapidApplication.create(System.getenv())

    fun start() = rapidsConnection.start()
}

fun main() {
    App().start()
}

